# Required metadata
sonar.projectKey=10pshine-notes-app-raja
sonar.projectName=Notes App (Raja Abdul Rafay)
sonar.projectVersion=1.0

# Path to source directories (backend and frontend)
sonar.sources=backend/src,frontend/src

# Exclude dependencies and build artifacts from analysis
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.test.tsx,frontend/vite.config.js,frontend/eslint.config.js

# Source encoding
sonar.sourceEncoding=UTF-8

# JavaScript/TypeScript Specifics
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx